
-- 1. Create Table
CREATE TABLE IF NOT EXISTS "PartnersApp"."Names" (
    "Id" SERIAL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Sex" TEXT NOT NULL -- 'Male' or 'Female'
);

-- 2. Disable RLS (Public Read)
ALTER TABLE "PartnersApp"."Names" DISABLE ROW LEVEL SECURITY;

-- 3. Grant Permissions
GRANT SELECT ON "PartnersApp"."Names" TO anon, authenticated, service_role;

-- 4. Insert Male Names
INSERT INTO "PartnersApp"."Names" ("Name", "Sex") VALUES
('Adam', 'Male'), ('Adaś', 'Male'), ('Adrian', 'Male'), ('Adrianek', 'Male'), ('Alan', 'Male'), ('Alanek', 'Male'), 
('Aleksander', 'Male'), ('Olek', 'Male'), ('Aleksy', 'Male'), ('Aleksik', 'Male'), ('Andrzej', 'Male'), ('Andrzejek', 'Male'), 
('Antoni', 'Male'), ('Antek', 'Male'), ('Arkadiusz', 'Male'), ('Arek', 'Male'), ('Artur', 'Male'), ('Artek', 'Male'), 
('Bartłomiej', 'Male'), ('Bartek', 'Male'), ('Bartosz', 'Male'), ('Bartek', 'Male'), ('Błażej', 'Male'), ('Błażejek', 'Male'), 
('Bogdan', 'Male'), ('Boguś', 'Male'), ('Bogumił', 'Male'), ('Bogunio', 'Male'), ('Bogusław', 'Male'), ('Boguś', 'Male'), 
('Bolesław', 'Male'), ('Bolek', 'Male'), ('Borys', 'Male'), ('Borysek', 'Male'), ('Bruno', 'Male'), ('Brunio', 'Male'), 
('Cezary', 'Male'), ('Czarek', 'Male'), ('Cyprian', 'Male'), ('Cyprianek', 'Male'), ('Czesław', 'Male'), ('Czesio', 'Male'), 
('Damian', 'Male'), ('Damianek', 'Male'), ('Daniel', 'Male'), ('Danielek', 'Male'), ('Dariusz', 'Male'), ('Darek', 'Male'), 
('Dawid', 'Male'), ('Dawidek', 'Male'), ('Dominik', 'Male'), ('Dominiczek', 'Male'), ('Edward', 'Male'), ('Edzio', 'Male'), 
('Emil', 'Male'), ('Emilek', 'Male'), ('Ernest', 'Male'), ('Ernestek', 'Male'), ('Eryk', 'Male'), ('Eryczek', 'Male'), 
('Eugeniusz', 'Male'), ('Gienek', 'Male'), ('Fabian', 'Male'), ('Fabianek', 'Male'), ('Feliks', 'Male'), ('Feluś', 'Male'), 
('Filip', 'Male'), ('Filipek', 'Male'), ('Franciszek', 'Male'), ('Franek', 'Male'), ('Fryderyk', 'Male'), ('Fryderyczek', 'Male'), 
('Gabriel', 'Male'), ('Gabryś', 'Male'), ('Gracjan', 'Male'), ('Gracjanek', 'Male'), ('Grzegorz', 'Male'), ('Grzesiek', 'Male'), 
('Gustaw', 'Male'), ('Gutek', 'Male'), ('Henryk', 'Male'), ('Henio', 'Male'), ('Hubert', 'Male'), ('Hubertek', 'Male'), 
('Ignacy', 'Male'), ('Ignaś', 'Male'), ('Igor', 'Male'), ('Igorek', 'Male'), ('Ireneusz', 'Male'), ('Irek', 'Male'), 
('Iwo', 'Male'), ('Iwek', 'Male'), ('Jacek', 'Male'), ('Jacuś', 'Male'), ('Jakub', 'Male'), ('Kuba', 'Male'), 
('Jan', 'Male'), ('Jasiek', 'Male'), ('Janusz', 'Male'), ('Januszek', 'Male'), ('Jarosław', 'Male'), ('Jarek', 'Male'), 
('Jerzy', 'Male'), ('Jurek', 'Male'), ('Jeremi', 'Male'), ('Jeremek', 'Male'), ('Joachim', 'Male'), ('Joachimek', 'Male'), 
('Józef', 'Male'), ('Józio', 'Male'), ('Julian', 'Male'), ('Julek', 'Male'), ('Juliusz', 'Male'), ('Julek', 'Male'), 
('Kacper', 'Male'), ('Kacperek', 'Male'), ('Kajetan', 'Male'), ('Kajtek', 'Male'), ('Kamil', 'Male'), ('Kamilek', 'Male'), 
('Karol', 'Male'), ('Karolek', 'Male'), ('Kazimierz', 'Male'), ('Kazio', 'Male'), ('Konrad', 'Male'), ('Konradek', 'Male'), 
('Kornel', 'Male'), ('Kornelek', 'Male'), ('Krystian', 'Male'), ('Krystianek', 'Male'), ('Krzysztof', 'Male'), ('Krzysiek', 'Male'), 
('Ksawery', 'Male'), ('Ksawerek', 'Male'), ('Leon', 'Male'), ('Leonek', 'Male'), ('Leonard', 'Male'), ('Leonuś', 'Male'), 
('Leszek', 'Male'), ('Lesio', 'Male'), ('Lucjan', 'Male'), ('Lucek', 'Male'), ('Ludwik', 'Male'), ('Ludwiczek', 'Male'), 
('Łukasz', 'Male'), ('Łukaszek', 'Male'), ('Maciej', 'Male'), ('Maciek', 'Male'), ('Maksymilian', 'Male'), ('Maks', 'Male'), 
('Marcel', 'Male'), ('Marcelek', 'Male'), ('Marcin', 'Male'), ('Marcinek', 'Male'), ('Marek', 'Male'), ('Mareczek', 'Male'), 
('Marian', 'Male'), ('Marianek', 'Male'), ('Mariusz', 'Male'), ('Mariuszek', 'Male'), ('Mateusz', 'Male'), ('Mati', 'Male'), 
('Maurycy', 'Male'), ('Maurycek', 'Male'), ('Michał', 'Male'), ('Michałek', 'Male'), ('Mieczysław', 'Male'), ('Mietek', 'Male'), 
('Mikołaj', 'Male'), ('Mikołajek', 'Male'), ('Milan', 'Male'), ('Milanek', 'Male'), ('Miłosz', 'Male'), ('Miłoszek', 'Male'), 
('Mirosław', 'Male'), ('Mirek', 'Male'), ('Natan', 'Male'), ('Natanek', 'Male'), ('Nataniel', 'Male'), ('Natanek', 'Male'), 
('Nikodem', 'Male'), ('Nikoś', 'Male'), ('Norbert', 'Male'), ('Norbertek', 'Male'), ('Olaf', 'Male'), ('Olafek', 'Male'), 
('Olgierd', 'Male'), ('Olgierdek', 'Male'), ('Oskar', 'Male'), ('Oskarek', 'Male'), ('Patryk', 'Male'), ('Patryczek', 'Male'), 
('Paweł', 'Male'), ('Pawełek', 'Male'), ('Piotr', 'Male'), ('Piotrek', 'Male'), ('Przemysław', 'Male'), ('Przemek', 'Male'), 
('Radosław', 'Male'), ('Radek', 'Male'), ('Rafał', 'Male'), ('Rafałek', 'Male'), ('Remigiusz', 'Male'), ('Remek', 'Male'), 
('Robert', 'Male'), ('Robercik', 'Male'), ('Roman', 'Male'), ('Romek', 'Male'), ('Ryszard', 'Male'), ('Rysiek', 'Male'), 
('Sebastian', 'Male'), ('Seba', 'Male'), ('Seweryn', 'Male'), ('Sewerynek', 'Male'), ('Sławomir', 'Male'), ('Sławek', 'Male'), 
('Stanisław', 'Male'), ('Staszek', 'Male'), ('Stefan', 'Male'), ('Stefanek', 'Male'), ('Sylwester', 'Male'), ('Sylwek', 'Male'), 
('Szczepan', 'Male'), ('Szczepanek', 'Male'), ('Szymon', 'Male'), ('Szymek', 'Male'), ('Tadeusz', 'Male'), ('Tadzio', 'Male'), 
('Teodor', 'Male'), ('Teodorek', 'Male'), ('Tobiasz', 'Male'), ('Tobiaszek', 'Male'), ('Tomasz', 'Male'), ('Tomek', 'Male'), 
('Tymon', 'Male'), ('Tymonek', 'Male'), ('Tymoteusz', 'Male'), ('Tymek', 'Male'), ('Wacław', 'Male'), ('Wacek', 'Male'), 
('Waldemar', 'Male'), ('Waldek', 'Male'), ('Wiesław', 'Male'), ('Wiesiek', 'Male'), ('Wiktor', 'Male'), ('Wiktorek', 'Male'), 
('Witold', 'Male'), ('Witek', 'Male'), ('Władysław', 'Male'), ('Władek', 'Male'), ('Wojciech', 'Male'), ('Wojtek', 'Male'), 
('Zbigniew', 'Male'), ('Zbyszek', 'Male'), ('Zdzisław', 'Male'), ('Zdzisiek', 'Male'), ('Zenon', 'Male'), ('Zenek', 'Male'), 
('Zygmunt', 'Male'), ('Zygmuś', 'Male');

-- 5. Insert Female Names
INSERT INTO "PartnersApp"."Names" ("Name", "Sex") VALUES
('Ada', 'Female'), ('Adusia', 'Female'), ('Adela', 'Female'), ('Adelka', 'Female'), ('Adrianna', 'Female'), ('Ada', 'Female'), 
('Agata', 'Female'), ('Agatka', 'Female'), ('Agnieszka', 'Female'), ('Aga', 'Female'), ('Aleksandra', 'Female'), ('Ola', 'Female'), 
('Alicja', 'Female'), ('Ala', 'Female'), ('Alina', 'Female'), ('Alinka', 'Female'), ('Amelia', 'Female'), ('Amelka', 'Female'), 
('Anastazja', 'Female'), ('Nastka', 'Female'), ('Anna', 'Female'), ('Ania', 'Female'), ('Antonina', 'Female'), ('Tosia', 'Female'), 
('Apolonia', 'Female'), ('Pola', 'Female'), ('Barbara', 'Female'), ('Basia', 'Female'), ('Beata', 'Female'), ('Beatka', 'Female'), 
('Bernadeta', 'Female'), ('Bernatka', 'Female'), ('Bianka', 'Female'), ('Bianeczka', 'Female'), ('Blanka', 'Female'), ('Blaneczka', 'Female'), 
('Bogumiła', 'Female'), ('Bogusia', 'Female'), ('Bogusława', 'Female'), ('Bogusia', 'Female'), ('Bożena', 'Female'), ('Bożenka', 'Female'), 
('Cecylia', 'Female'), ('Cecylka', 'Female'), ('Celina', 'Female'), ('Celinka', 'Female'), ('Czesława', 'Female'), ('Czesia', 'Female'), 
('Dagmara', 'Female'), ('Daga', 'Female'), ('Danuta', 'Female'), ('Danusia', 'Female'), ('Daria', 'Female'), ('Darka', 'Female'), 
('Dominika', 'Female'), ('Dominisia', 'Female'), ('Dorota', 'Female'), ('Dorotka', 'Female'), ('Edyta', 'Female'), ('Edytka', 'Female'), 
('Elena', 'Female'), ('Elenka', 'Female'), ('Eleonora', 'Female'), ('Ela', 'Female'), ('Eliza', 'Female'), ('Elizka', 'Female'), 
('Elżbieta', 'Female'), ('Ela', 'Female'), ('Emilia', 'Female'), ('Emilka', 'Female'), ('Ewa', 'Female'), ('Ewcia', 'Female'), 
('Ewelina', 'Female'), ('Ewelinka', 'Female'), ('Faustyna', 'Female'), ('Faustynka', 'Female'), ('Felicja', 'Female'), ('Felcia', 'Female'), 
('Gabriela', 'Female'), ('Gabrysia', 'Female'), ('Grażyna', 'Female'), ('Grażynka', 'Female'), ('Halina', 'Female'), ('Halinka', 'Female'), 
('Hanna', 'Female'), ('Hania', 'Female'), ('Helena', 'Female'), ('Helenka', 'Female'), ('Honorata', 'Female'), ('Honorka', 'Female'), 
('Iga', 'Female'), ('Igusia', 'Female'), ('Ilona', 'Female'), ('Ilonka', 'Female'), ('Irena', 'Female'), ('Irenka', 'Female'), 
('Iwona', 'Female'), ('Iwonka', 'Female'), ('Izabela', 'Female'), ('Iza', 'Female'), ('Jadwiga', 'Female'), ('Jadzia', 'Female'), 
('Jagoda', 'Female'), ('Jagódka', 'Female'), ('Janina', 'Female'), ('Janeczka', 'Female'), ('Joanna', 'Female'), ('Asia', 'Female'), 
('Jolanta', 'Female'), ('Jola', 'Female'), ('Józefa', 'Female'), ('Józia', 'Female'), ('Julia', 'Female'), ('Julka', 'Female'), 
('Julianna', 'Female'), ('Julka', 'Female'), ('Justyna', 'Female'), ('Justynka', 'Female'), ('Kalina', 'Female'), ('Kalinka', 'Female'), 
('Kamila', 'Female'), ('Kamilka', 'Female'), ('Karina', 'Female'), ('Karinka', 'Female'), ('Karolina', 'Female'), ('Karolka', 'Female'), 
('Katarzyna', 'Female'), ('Kasia', 'Female'), ('Kinga', 'Female'), ('Kingusia', 'Female'), ('Klara', 'Female'), ('Klarcia', 'Female'), 
('Klaudia', 'Female'), ('Klaudusia', 'Female'), ('Konstancja', 'Female'), ('Kostka', 'Female'), ('Kornelia', 'Female'), ('Nelka', 'Female'), 
('Krystyna', 'Female'), ('Krysia', 'Female'), ('Laura', 'Female'), ('Laurka', 'Female'), ('Lena', 'Female'), ('Lenka', 'Female'), 
('Lidia', 'Female'), ('Lidka', 'Female'), ('Liliana', 'Female'), ('Lila', 'Female'), ('Lucyna', 'Female'), ('Lucynka', 'Female'), 
('Ludwika', 'Female'), ('Ludka', 'Female'), ('Luiza', 'Female'), ('Luizka', 'Female'), ('Łucja', 'Female'), ('Łucynka', 'Female'), 
('Magdalena', 'Female'), ('Magda', 'Female'), ('Maja', 'Female'), ('Majeczka', 'Female'), ('Małgorzata', 'Female'), ('Małgosia', 'Female'), 
('Marcelina', 'Female'), ('Marcelka', 'Female'), ('Maria', 'Female'), ('Marysia', 'Female'), ('Marianna', 'Female'), ('Mania', 'Female'), 
('Mariola', 'Female'), ('Mariolka', 'Female'), ('Marta', 'Female'), ('Martusia', 'Female'), ('Martyna', 'Female'), ('Martynka', 'Female'), 
('Maryla', 'Female'), ('Marylka', 'Female'), ('Marzena', 'Female'), ('Marzenka', 'Female'), ('Matylda', 'Female'), ('Matyldzia', 'Female'), 
('Melania', 'Female'), ('Melka', 'Female'), ('Michalina', 'Female'), ('Misia', 'Female'), ('Mieczysława', 'Female'), ('Mietka', 'Female'), 
('Milena', 'Female'), ('Milenka', 'Female'), ('Mirosława', 'Female'), ('Mirka', 'Female'), ('Monika', 'Female'), ('Monisia', 'Female'), 
('Nadia', 'Female'), ('Nadusia', 'Female'), ('Natalia', 'Female'), ('Natalka', 'Female'), ('Nela', 'Female'), ('Nelka', 'Female'), 
('Nicola', 'Female'), ('Nicolka', 'Female'), ('Nina', 'Female'), ('Nineczka', 'Female'), ('Olga', 'Female'), ('Olunia', 'Female'), 
('Olimpia', 'Female'), ('Olimpka', 'Female'), ('Oliwia', 'Female'), ('Oliwka', 'Female'), ('Patrycja', 'Female'), ('Patryczka', 'Female'), 
('Paulina', 'Female'), ('Paulinka', 'Female'), ('Pola', 'Female'), ('Poleczka', 'Female'), ('Regina', 'Female'), ('Reginka', 'Female'), 
('Renata', 'Female'), ('Renatka', 'Female'), ('Rozalia', 'Female'), ('Rózia', 'Female'), ('Róża', 'Female'), ('Różyczka', 'Female'), 
('Sabina', 'Female'), ('Sabinka', 'Female'), ('Sandra', 'Female'), ('Sandrusia', 'Female'), ('Sara', 'Female'), ('Sarcia', 'Female'), 
('Stanisława', 'Female'), ('Stasia', 'Female'), ('Stefania', 'Female'), ('Stefa', 'Female'), ('Sylwia', 'Female'), ('Sylwunia', 'Female'), 
('Tamara', 'Female'), ('Tamarka', 'Female'), ('Teresa', 'Female'), ('Tereska', 'Female'), ('Urszula', 'Female'), ('Ula', 'Female'), 
('Weronika', 'Female'), ('Weronisia', 'Female'), ('Wiktoria', 'Female'), ('Wiktusia', 'Female'), ('Wioletta', 'Female'), ('Wiola', 'Female'), 
('Wanda', 'Female'), ('Wandzia', 'Female'), ('Wiesława', 'Female'), ('Wiesia', 'Female'), ('Zdzisława', 'Female'), ('Zdzisia', 'Female'), 
('Zofia', 'Female'), ('Zosia', 'Female'), ('Zuzanna', 'Female'), ('Zuzia', 'Female'), ('Żaneta', 'Female'), ('Żanetka', 'Female');
